name: Manual version PRs

on:
  workflow_dispatch:
    inputs:
      shopware_version:
        description: "Shopware version"
        required: true
        type: string
      php_version:
        description: "PHP version"
        required: false
        type: string
        default: "8.2"
      trigger_default_schema:
        description: "Trigger schema"
        required: false
        type: boolean
        default: true

jobs:
  generate-trunk:
    if: ${{ inputs.trigger_default_schema }}
    uses: ./.github/workflows/base_schema.yml
    with:
      shopware_version: ${{ inputs.shopware_version }}
      php_version: ${{ inputs.php_version }}
    secrets: inherit
